import type { People } from "./types";
export const myProfile: People = {
  id: "a5566778-8899-00aa-bbcc-ddeeff112233",
  name: "မေသူကျော်",
  age: "31",
  intro: "ဘာသာစကား သင်ကြားရတာကို ဝါသနာပါတဲ့ ဆရာမတစ်ယောက်ပါ။",
  imageUrl: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb",
  location: "လားရှိုးမြို့",
  like: false,
  match: false,
  isOnline: false,
}
export const burmesePeople: People[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    name: "အောင်မင်းခန့်",
    age: "28",
    intro: "ကျွန်တော်က နည်းပညာကို ဝါသနာပါတဲ့ ဆော့ဖ်ဝဲအင်ဂျင်နီယာတစ်ယောက်ပါ။",
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    location: "ရန်ကုန်မြို့",
    like: true,
    match: true,
    isOnline: true,
  },
  {
    id: "721e4b33-12a4-4921-b3b4-123456789012",
    name: "နန်းစန္ဒာလင်း",
    age: "24",
    intro: "ခရီးသွားရတာနဲ့ ဓာတ်ပုံရိုက်ရတာကို အရမ်းနှစ်သက်ပါတယ်။",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    location: "တောင်ကြီးမြို့",
    like: true,
    match: true,
    isOnline: true,
  },
  {
    id: "a33b22c1-d44e-4f55-8899-aabbccddeeff",
    name: "ကျော်ဇေယျာ",
    age: "32",
    intro: "စီးပွားရေးလုပ်ငန်းရှင်တစ်ဦးဖြစ်ပြီး စာဖတ်ခြင်းကို ဝါသနာပါသူပါ။",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    location: "မန္တလေးမြို့",
    like: true,
    match: true,
    isOnline: true,
  },
  {
    id: "f9988776-6655-4433-2211-009988776655",
    name: "သုသုဝင်း",
    age: "26",
    intro: "အနုပညာနဲ့ ဒီဇိုင်းပိုင်းကို စိတ်ဝင်စားတဲ့ ဂရပ်ဖစ်ဒီဇိုင်နာပါ။",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    location: "နေပြည်တော်",
    like: true,
    match: true,
    isOnline: false,
  },
  {
    id: "b1122334-4455-6677-8899-00aabbccddee",
    name: "မင်းထက်အောင်",
    age: "30",
    intro: "အားကစားလုပ်ရတာ ကြိုက်နှစ်သက်တဲ့ ကာယဆရာတစ်ယောက်ပါ။",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    location: "မော်လမြိုင်မြို့",
    like: true,
    match: false,
    isOnline: false,
  },
  {
    id: "c4455667-7788-9900-aabb-ccddeeff1122",
    name: "အိချောပို",
    age: "22",
    intro: "တက္ကသိုလ်ကျောင်းသူတစ်ဦးဖြစ်ပြီး ဂီတကို မြတ်နိုးသူပါ။",
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    location: "ပုသိမ်မြို့",
    like: true,
    match: false,
    isOnline: false,
  },
  {
    id: "d7788990-00aa-bbcc-ddee-ff1122334455",
    name: "ဇော်လင်းထက်",
    age: "35",
    intro: "ချက်ပြုတ်ရတာ ဝါသနာပါတဲ့ စားဖိုမှူးတစ်ဦးဖြစ်ပါတယ်။",
    imageUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce",
    location: "ပြင်ဦးလွင်မြို့",
    like: false,
    match: false,
    isOnline: false,
  },
  {
    id: "e1122334-4455-6677-8899-aabbccddeeff",
    name: "ခင်နှင်းဝေ",
    age: "29",
    intro: "ကျန်းမာရေးစောင့်ရှောက်မှုပေးရတာကို ပျော်ရွှင်တဲ့ ဆရာဝန်မလေးပါ။",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    location: "မြစ်ကြီးနားမြို့",
    like: false,
    match: false,
    isOnline: false,
  },
  {
    id: "f3344556-6677-8899-00aa-bbccddeeff11",
    name: "ကောင်းခန့်ကျော်",
    age: "27",
    intro: "သဘာဝပတ်ဝန်းကျင် ထိန်းသိမ်းရေးသမားတစ်ဦးပါ။",
    imageUrl: "https://images.unsplash.com/photo-1552058544-f2b08422138a",
    location: "စစ်တွေမြို့",
    like: false,
    match: false,
    isOnline: false,
  },
];


export const matchPeopleList: People[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    name: "အောင်မင်းခန့်",
    age: "28",
    intro: "ကျွန်တော်က နည်းပညာကို ဝါသနာပါတဲ့ ဆော့ဖ်ဝဲအင်ဂျင်နီယာတစ်ယောက်ပါ။",
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    location: "ရန်ကုန်မြို့",
    like: true,
    match: true,
    isOnline: true,
    messages: [
      {
        id: "m1",
        sender: "အောင်မင်းခန့်",
        text: "ဟိုင်း... ပရောဂျက်အခြေအနေ ဘယ်လိုရှိလဲ။",
        timestamp: "2026-02-18T10:30:00Z",
        isRead: true,
      },
      {
        id: "m2",
        sender: "You",
        text: "အဆင်ပြေပါတယ်။ အခုပဲ စစ်ကြည့်နေတာ။",
        timestamp: "2026-02-18T10:35:00Z",
        isRead: true,
      },
      {
        id: "m3",
        sender: "အောင်မင်းခန့်",
        text: "ဟုတ်ကဲ့ဗျ၊ အမှားအယွင်းလေးတွေရှိရင် ပြောပြပေးပါဦး။",
        timestamp: "2026-02-18T10:37:00Z",
        isRead: true,
      },
      {
        id: "m4",
        sender: "You",
        text: "ဒေတာတွေကတော့ မှန်နေပြီ၊ ဒီဇိုင်းပိုင်း နည်းနည်းပြင်ဖို့ လိုမယ်ထင်တယ်။",
        timestamp: "2026-02-18T10:40:00Z",
        isRead: true,
      },
      {
        id: "m5",
        sender: "အောင်မင်းခန့်",
        text: "ဘယ်နေရာကို အဓိက ပြင်စေချင်တာလဲခင်ဗျာ?",
        timestamp: "2026-02-18T10:42:00Z",
        isRead: true,
      },
      {
        id: "m6",
        sender: "You",
        text: "Mobile View မှာ Button တွေက အရမ်းသေးနေသလိုပဲ။",
        timestamp: "2026-02-18T10:45:00Z",
        isRead: true,
      },
      {
        id: "m7",
        sender: "အောင်မင်းခန့်",
        text: "ဪ ဟုတ်ကဲ့၊ အဲဒါကို DaisyUI က btn-md သုံးပြီး ပြန်ပြင်လိုက်ပါ့မယ်။",
        timestamp: "2026-02-18T10:48:00Z",
        isRead: true,
      },
      {
        id: "m8",
        sender: "You",
        text: "အိုကေဗျာ၊ အဲဒါဆိုရင်တော့ အတော်လေး အဆင်ပြေသွားပြီ။",
        timestamp: "2026-02-18T10:50:00Z",
        isRead: true,
      },
      {
        id: "m9",
        sender: "အောင်မင်းခန့်",
        text: "ကျေးဇူးပါပဲ! ပြီးရင် ကျွန်တော် ပြန်ပို့ပေးပါ့မယ်။",
        timestamp: "2026-02-18T10:52:00Z",
        isRead: true,
      },
      {
        id: "m10",
        sender: "You",
        text: "ရပါတယ်၊ အေးဆေးလုပ်ပါ။ စောင့်နေမယ်။",
        timestamp: "2026-02-18T10:55:00Z",
        isRead: true,
      },
      {
        id: "m11",
        sender: "အောင်မင်းခန့်",
        text: "နောက်တစ်ခုက Animation လေးတွေရော ထည့်စေချင်သေးလား?",
        timestamp: "2026-02-18T10:58:00Z",
        isRead: true,
      },
      {
        id: "m12",
        sender: "You",
        text: "Match ဖြစ်တဲ့အချိန် Heart animation လေးဆိုရင်တော့ မိုက်မယ်။",
        timestamp: "2026-02-18T11:02:00Z",
        isRead: true,
      }
    ]
  },
  {
    id: "721e4b33-12a4-4921-b3b4-123456789012",
    name: "နန်းစန္ဒာလင်း",
    age: "24",
    intro: "ခရီးသွားရတာနဲ့ ဓာတ်ပုံရိုက်ရတာကို အရမ်းနှစ်သက်ပါတယ်။",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    location: "တောင်ကြီးမြို့",
    like: true,
    isOnline: true,
    match: true,
    messages: [
      {
        id: "m3",
        sender: "နန်းစန္ဒာလင်း",
        text: "နေကောင်းလား? ဒီနေ့ အားလားခင်ဗျ။",
        timestamp: "2026-02-18T09:00:00Z",
        isRead: true,
      },
      {
        id: "m4",
        sender: "You",
        text: "နေကောင်းပါတယ်၊ ဒီနေ့တော့ အလုပ်လေး နည်းနည်းရှိနေလို့။ ဘာဖြစ်လို့လဲဟင်?",
        timestamp: "2026-02-18T09:05:00Z",
        isRead: true,
      },
      {
        id: "m5",
        sender: "နန်းစန္ဒာလင်း",
        text: "ဪ... တောင်ကြီးမှာ ပွဲတော်ရှိလို့ လိုက်ခဲ့မလားလို့ မေးမလို့ပါ။",
        timestamp: "2026-02-18T09:08:00Z",
        isRead: true,
      },
      {
        id: "m6",
        sender: "You",
        text: "တကယ်လား! ဘာပွဲတော်လဲ? စိတ်ဝင်စားစရာပဲ။",
        timestamp: "2026-02-18T09:12:00Z",
        isRead: true,
      },
      {
        id: "m7",
        sender: "နန်းစန္ဒာလင်း",
        text: "မီးပုံးပျံပွဲတော်လေ၊ အရမ်းလှတာ။ ဓာတ်ပုံရိုက်လို့လည်း ကောင်းတယ်။",
        timestamp: "2026-02-18T09:15:00Z",
        isRead: true,
      },
      {
        id: "m8",
        sender: "You",
        text: "ဓာတ်ပုံရိုက်ဖို့ဆိုရင်တော့ မငြင်းတော့ဘူး။ အလုပ်ကို မြန်မြန်ဖြတ်လိုက်မယ်။",
        timestamp: "2026-02-18T09:18:00Z",
        isRead: true,
      },
      {
        id: "m9",
        sender: "နန်းစန္ဒာလင်း",
        text: "ဟဲဟဲ၊ အိုကေ။ အဲဒါဆို ညနေ ၆ နာရီလောက်မှ ဆုံကြမလား?",
        timestamp: "2026-02-18T09:20:00Z",
        isRead: true,
      },
      {
        id: "m10",
        sender: "You",
        text: "ရတယ်၊ နေရာလေးသာ ပို့ထားပေးပါ။ အရောက်လာခဲ့မယ်။",
        timestamp: "2026-02-18T09:22:00Z",
        isRead: true,
      },
      {
        id: "m11",
        sender: "နန်းစန္ဒာလင်း",
        text: "အောက်က Location လေးအတိုင်း လာခဲ့နော်။",
        timestamp: "2026-02-18T09:25:00Z",
        isRead: true,
      },
      {
        id: "m12",
        sender: "နန်းစန္ဒာလင်း",
        text: "📍 အဝေရာ မီးပုံးပျံကွင်း",
        timestamp: "2026-02-18T09:25:30Z",
        isRead: true,
      },
      {
        id: "m13",
        sender: "You",
        text: "မြင်ပြီ။ တွေ့မယ်နော်!",
        timestamp: "2026-02-18T09:28:00Z",
        isRead: true,
      },
      {
        id: "m14",
        sender: "နန်းစန္ဒာလင်း",
        text: "အိုကေ၊ လမ်းမှာ ဂရုစိုက်လာပါ။ အိုကေ၊ လမ်းမှာ ဂရုစိုက်လာပါ။ အိုကေ၊ လမ်းမှာ ဂရုစိုက်လာပါ။ အိုကေ၊ လမ်းမှာ ဂရုစိုက်လာပါ။",
        timestamp: "2026-02-18T09:30:00Z",
        isRead: true,
      }
    ]
  },
  {
    id: "a33b22c1-d44e-4f55-8899-aabbccddeeff",
    name: "ကျော်ဇေယျာ",
    age: "32",
    intro: "စီးပွားရေးလုပ်ငန်းရှင်တစ်ဦးဖြစ်ပြီး စာဖတ်ခြင်းကို ဝါသနာပါသူပါ။",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    location: "မန္တလေးမြို့",
    like: true,
    isOnline: true,
    match: true,
    messages: []
  },
  {
    id: "f9988776-6655-4433-2211-009988776655",
    name: "သုသုဝင်း",
    age: "26",
    intro: "အနုပညာနဲ့ ဒီဇိုင်းပိုင်းကို စိတ်ဝင်စားတဲ့ ဂရပ်ဖစ်ဒီဇိုင်နာပါ။",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    location: "နေပြည်တော်",
    like: true,
    isOnline: false,
    match: true,
    messages: [
      {
        id: "m4",
        sender: "သုသုဝင်း",
        text: "ဒီဇိုင်းအသစ် ပို့လိုက်ပြီနော်။ ကြည့်ပေးပါဦး။",
        timestamp: "2026-02-17T22:15:00Z",
        isRead: true,
      },
      {
        id: "m5",
        sender: "You",
        text: "ဟုတ်ကဲ့ဗျ၊ အခုပဲ ဖွင့်ကြည့်လိုက်ပြီ။ ကာလာရွေးထားတာ အရမ်းမိုက်တယ်!",
        timestamp: "2026-02-17T22:20:00Z",
        isRead: true,
      },
      {
        id: "m6",
        sender: "သုသုဝင်း",
        text: "ကျေးဇူးပါရှင်။ Font လေးကိုရော အဆင်ပြေရဲ့လား? နည်းနည်းများ ကြီးနေလားလို့။",
        timestamp: "2026-02-17T22:22:00Z",
        isRead: true,
      },
      {
        id: "m7",
        sender: "You",
        text: "Heading ကတော့ အိုကေတယ်၊ ဒါပေမယ့် Body text ကို နည်းနည်းလေး ပိုကျဉ်းပေးလို့ရမလား။",
        timestamp: "2026-02-17T22:25:00Z",
        isRead: true,
      },
      {
        id: "m8",
        sender: "သုသုဝင်း",
        text: "ရပါတယ်ရှင်။ Line height ကို နည်းနည်းလျှော့လိုက်ရင် ပိုကြည့်ကောင်းသွားမယ် ထင်တယ်။",
        timestamp: "2026-02-17T22:28:00Z",
        isRead: true,
      },
      {
        id: "m9",
        sender: "You",
        text: "ဟုတ်တယ်၊ အဲဒါလေးပဲ။ ကျန်တာကတော့ Perfect ပဲဗျ။",
        timestamp: "2026-02-17T22:30:00Z",
        isRead: true,
      },
      {
        id: "m10",
        sender: "သုသုဝင်း",
        text: "အိုကေရှင့်၊ ဒါဆိုရင် ဖိုင်ကို Export ထုတ်ပြီး Google Drive ထဲ တင်ပေးထားမယ်နော်။",
        timestamp: "2026-02-17T22:32:00Z",
        isRead: true,
      },
      {
        id: "m11",
        sender: "You",
        text: "ဟုတ်ကဲ့၊ လင့်ခ်လေး ဒီမှာပဲ ချပေးထားပါ။",
        timestamp: "2026-02-17T22:35:00Z",
        isRead: true,
      },
      {
        id: "m12",
        sender: "သုသုဝင်း",
        text: "တင်ပြီးပါပြီ! 📁 final-design-v2.zip",
        timestamp: "2026-02-17T22:40:00Z",
        isRead: true,
      },
      {
        id: "m13",
        sender: "သုသုဝင်း",
        text: "နောက်ထပ် တစ်ခုခု ပြင်ချင်သေးရင် အချိန်မရွေး ပြောပါနော်။",
        timestamp: "2026-02-17T22:41:00Z",
        isRead: true,
      },
      {
        id: "m14",
        sender: "You",
        text: "ကျေးဇူးအများကြီးတင်ပါတယ်ဗျ။ နောက်ထပ် ပရောဂျက်တွေရှိရင်လည်း ထပ်အပ်ပါဦးမယ်။",
        timestamp: "2026-02-17T22:45:00Z",
        isRead: true,
      },
      {
        id: "m15",
        sender: "သုသုဝင်း",
        text: "ဟုတ်ကဲ့ပါရှင့်၊ ကောင်းသောညလေး ဖြစ်ပါစေရှင်။ 😊",
        timestamp: "2026-02-17T22:47:00Z",
        isRead: true,
      }
    ]
  },
];